---
- name: Change background gnome
  hosts: localhost
  vars:
    user: cg
    bg: bg1.jpg
  tasks:
    - name: Install python-psutil package
      become: yes
      dnf: 
        name: python-psutil
        state: present

    - name: Copy wallpaper file
      copy: src='images/{{ bg }}' dest='/home/{{ user }}/.{{ bg }}' owner='{{ user }}' group='{{ user }}' mode=600

    - name: Set GNOME wallpaper
      dconf: key="/org/gnome/desktop/background/picture-uri" value="'file:///home/{{ user }}/.{{ bg }}'"

    - name: Copy lockscreenfile
      copy: src='images/{{ bg }}' dest='/home/{{ user }}/.{{ bg }}' owner={{ user }} group={{ user }} mode=600

    - name: Set lock screen background
      dconf: key="/org/gnome/desktop/screensaver/picture-uri" value="'file:///home/jay/.{{ bg }}'"
