---
- name: Instalar extensiones de Gnome Shell desde archivos ZIP
  hosts: localhost
  become: yes
  vars:
    extension_urls:
      - 'https://extensions.gnome.org/extension-data/dash-to-paneljderose9.github.com.v56.shell-extension.zip'

  tasks:
    - name: Verificar si jq está instalado
      command: rpm -q jq
      register: jq_installed
      ignore_errors: yes

    - name: Instalar jq si no está instalado
      dnf:
        name: jq
        state: present
      when: jq_installed.rc != 0

    - name: Crear directorio para las extensiones de Gnome Shell
      file:
        path: ~/.local/share/gnome-shell/extensions/
        state: directory

    - name: Descargar archivos ZIP desde las URLs
      get_url:
        url: '{{ item }}'
        dest: "/tmp/{{ item | regex_replace('https?://', '') | regex_replace('/', '_') }}"
      loop: '{{ extension_urls }}'

    - name: Extraer y activar extensiones de Gnome Shell desde archivos ZIP
      block:
        - name: Iterar sobre archivos ZIP
          unarchive:
            src: "/tmp/{{ item | regex_replace('https?://', '') | regex_replace('/', '_') }}"
            dest: '~/.local/share/gnome-shell/extensions/'
            remote_src: yes
          loop: '{{ extension_urls }}'
          register: unzip_result

        - name: Reiniciar Gnome Shell para activar las extensiones
          command: sudo systemctl restart gdm
          async: 0
          poll: 0
      when: unzip_result | changed

    - name: Mostrar mensaje de éxito
      debug:
        msg: 'Las extensiones de Gnome Shell se han instalado y activado correctamente.'
      when: unzip_result | changed
# ---
# - name: Instalar extensiones de GNOME Shell en Fedora
#   hosts: localhost
#   become: yes
#   tasks:
#     - name: Instalar paquetes necesarios para extensiones GNOME
#       dnf:
#         name:
#           - gnome-tweaks
#         state: present

#     - name: Instalar las extensiones de GNOME Shell
#       ansible.builtin.debug: gnome-extensions install --force {{ item }}
#       loop:
#         - dash-to-panel@jderose9.github.com
#         - arc-menu@arcmenu.com
#         - netspeed@hedayaty.gmail.com
#         - workspace-indicator@gnome-shell-extensions.gcampax.github.com
#         - wintile@nowsci.com
#         - gnome-shell-extension-vitals@eunhak.lee@gmail.com
#         - clipboard-indicator@tudmotu.com
#         - user-themes@gnome-shell-extensions.gcampax.github.com
#         - bluetooth-quick-connect@bjarosze.gmail.com
#         - just-perfection@gns.gnomewebapps.com
#         - services-systemd@github.com
#         - sound-output-device-chooser@kgshank.net
#         - sound-input-device-chooser@kgshank.net
#         - gsconnect@andyholmes.github.io
#         - mediaplayer@patapon.info
#         - apps-menu@gnome-shell-extensions.gcampax.github.com
#         - tray-icons@hliu.org

#     # - name: Habilitar las extensiones instaladas
#     #   ansible.builtin.shell: gnome-extensions enable {{ item }}
#     #   loop:
#     #     - dash-to-panel@jderose9.github.com
#     #     - arc-menu@arcmenu.com
#     #     - netspeed@hedayaty.gmail.com
#     #     - workspace-indicator@gnome-shell-extensions.gcampax.github.com
#     #     - wintile@nowsci.com
#     #     - gnome-shell-extension-vitals@eunhak.lee@gmail.com
#     #     - clipboard-indicator@tudmotu.com
#     #     - user-themes@gnome-shell-extensions.gcampax.github.com
#     #     - bluetooth-quick-connect@bjarosze.gmail.com
#     #     - just-perfection@gns.gnomewebapps.com
#     #     - services-systemd@github.com
#     #     - sound-output-device-chooser@kgshank.net
#     #     - sound-input-device-chooser@kgshank.net
#     #     - gsconnect@andyholmes.github.io
#     #     - mediaplayer@patapon.info
#     #     - apps-menu@gnome-shell-extensions.gcampax.github.com
#     #     - tray-icons@hliu.org
