---
- name: Install flatpak apps
  hosts: localhost
  become: yes
  vars:
    flatpak_apps:
      - com.visualstudio.code
      - com.getpostman.Postman
      - com.brave.Browser
      - org.flameshot.Flameshot
      - io.dbeaver.DBeaverCommunity

  tasks:
    - name: Install Flatpak
      dnf:
        name: flatpak
        state: present

    - name: Add the Gnome flatpak remote to the system installation
      community.general.flatpak_remote:
        name: gnome
        state: present
        flatpakrepo_url: https://sdk.gnome.org/gnome-apps.flatpakrepo

    - name: Add the flathub flatpak repository remote to the user installation
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

    - name: Update Flatpak
      flatpak:
        subcommand: update

    - name: Install Flatpak applications
      flatpak:
        name: '{{ item }}'
        remote: flathub
        state: present
      loop: '{{ flatpak_apps }}'
