---
- name: Instalar extensiones de Gnome Shell desde múltiples URLs
  hosts: localhost
  become: yes
  vars:
    extension_urls:
      - 'https://extensions.gnome.org/extension-data/dash-to-paneljderose9.github.com.v56.shell-extension.zip'

  tasks:
    - name: Instalar jq si no está instalado
      dnf:
        name: jq
        state: present

    - name: Crear directorio para las extensiones de Gnome Shell
      file:
        path: ~/.local/share/gnome-shell/extensions/
        state: directory

    - name: Descargar archivos ZIP desde las URLs y extraer extensiones
      shell: |
        echo "URL $extension_urls"
        for url in "${ extension_urls }"; do
          uuid=$(curl -s "$url" | unzip -p - metadata.json | jq -r '.uuid')
          echo "::::::::url $url"
          echo "============ uuid: $uuid"
          if [ -z "$uuid" ]; then
            echo "[ERROR] No se pudo extraer el UUID de $url."
            continue
          fi
          dest_dir="~/.local/share/gnome-shell/extensions/$uuid"
          mkdir -p "$dest_dir"
          curl -o "/tmp/$uuid.zip" "$url"
          unzip -q -o "/tmp/$uuid.zip" -d "$dest_dir"
          rm -f "/tmp/$uuid.zip"
        done
      register: download_result

    - name: Reiniciar Gnome Shell para activar las extensiones
      command: echo "Reiniciar gnome"
      async: 0
      poll: 0

    - name: Comprobar que las extensiones se han instalado
      command: ls -A1 ~/.local/share/gnome-shell/extensions/
      register: installed_extensions

    - name: Mostrar mensaje de éxito
      debug:
        msg: 'Las extensiones de Gnome Shell se han instalado en ~/.local/share/gnome-shell/extensions/'
      when: download_result.rc == 0 and installed_extensions.stdout_lines | length > 0
# ---
# - name: Instalar extensiones de GNOME Shell en Fedora
#   hosts: localhost
#   become: yes
#   tasks:
#     - name: Instalar paquetes necesarios para extensiones GNOME
#       dnf:
#         name:
#           - gnome-tweaks
#         state: present

#     - name: Instalar las extensiones de GNOME Shell
#       ansible.builtin.debug: gnome-extensions install --force {{ item }}
#       loop:
#         - dash-to-panel@jderose9.github.com
#         - arc-menu@arcmenu.com
#         - netspeed@hedayaty.gmail.com
#         - workspace-indicator@gnome-shell-extensions.gcampax.github.com
#         - wintile@nowsci.com
#         - gnome-shell-extension-vitals@eunhak.lee@gmail.com
#         - clipboard-indicator@tudmotu.com
#         - user-themes@gnome-shell-extensions.gcampax.github.com
#         - bluetooth-quick-connect@bjarosze.gmail.com
#         - just-perfection@gns.gnomewebapps.com
#         - services-systemd@github.com
#         - sound-output-device-chooser@kgshank.net
#         - sound-input-device-chooser@kgshank.net
#         - gsconnect@andyholmes.github.io
#         - mediaplayer@patapon.info
#         - apps-menu@gnome-shell-extensions.gcampax.github.com
#         - tray-icons@hliu.org

#     # - name: Habilitar las extensiones instaladas
#     #   ansible.builtin.shell: gnome-extensions enable {{ item }}
#     #   loop:
#     #     - dash-to-panel@jderose9.github.com
#     #     - arc-menu@arcmenu.com
#     #     - netspeed@hedayaty.gmail.com
#     #     - workspace-indicator@gnome-shell-extensions.gcampax.github.com
#     #     - wintile@nowsci.com
#     #     - gnome-shell-extension-vitals@eunhak.lee@gmail.com
#     #     - clipboard-indicator@tudmotu.com
#     #     - user-themes@gnome-shell-extensions.gcampax.github.com
#     #     - bluetooth-quick-connect@bjarosze.gmail.com
#     #     - just-perfection@gns.gnomewebapps.com
#     #     - services-systemd@github.com
#     #     - sound-output-device-chooser@kgshank.net
#     #     - sound-input-device-chooser@kgshank.net
#     #     - gsconnect@andyholmes.github.io
#     #     - mediaplayer@patapon.info
#     #     - apps-menu@gnome-shell-extensions.gcampax.github.com
#     #     - tray-icons@hliu.org
