---
- name: Install flatpak apps
  hosts: localhost
  become: yes
  vars:
    flatpak_apps:
      - com.visualstudio.code
      - com.getpostman.Postman
      - com.brave.Browser
      - org.flameshot.Flameshot
      - io.dbeaver.DBeaverCommunity

  tasks:
    - name: Install Flatpak
      dnf:
        name: flatpak
        state: present

    - name: Add the flathub flatpak repository remote to the user installation
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

    - name: Update Flatpak
      shell: flatpak update --noninteractive

    - name: Install Flatpak applications
      flatpak:
        name: '{{ item }}'
        remote: flathub
        state: present
      loop: '{{ flatpak_apps }}'
