---
- name: Instalar Docker en Fedora
  hosts: localhost
  become: yes
  tasks:
    - name: Instalar dnf-plugins-core
      dnf:
        name: dnf-plugins-core
        state: present

    - name: Install docker
      ansible.builtin.script: /scripts/install-docker-fedora.sh
