---
- name: Instalar extensiones de Gnome Shell desde múltiples URLs
  hosts: localhost
  become: yes
  vars:
    extension_urls:
      - 'https://extensions.gnome.org/extension-data/dash-to-paneljderose9.github.com.v56.shell-extension.zip'
      - 'https://extensions.gnome.org/extension-data/arcmenuarcmenu.com.v48.shell-extension.zip'
      - 'https://extensions.gnome.org/extension-data/netspeedhedayaty.gmail.com.v34.shell-extension.zip'
      - 'https://extensions.gnome.org/extension-data/horizontal-workspace-indicatortty2.io.v19.shell-extension.zip'
      - 'https://extensions.gnome.org/extension-data/wintilenowsci.com.v15.shell-extension.zip'
      - 'https://extensions.gnome.org/extension-data/VitalsCoreCoding.com.v61.shell-extension.zip'
      - 'https://extensions.gnome.org/extension-data/clipboard-indicatorDieg0Js.github.io.v4.shell-extension.zip'
      - 'https://extensions.gnome.org/extension-data/user-themegnome-shell-extensions.gcampax.github.com.v51.shell-extension.zip'
      - 'https://extensions.gnome.org/extension-data/bluetooth-quick-connectbjarosze.gmail.com.v37.shell-extension.zip'
      - 'https://extensions.gnome.org/extension-data/just-perfection-desktopjust-perfection.v26.shell-extension.zip'
      - 'https://extensions.gnome.org/extension-data/battery-indicator-iconDeminder.v8.shell-extension.zip'
      - 'https://extensions.gnome.org/extension-data/espressocoadmunkee.github.com.v8.shell-extension.zip'
      - 'https://extensions.gnome.org/extension-data/gsconnectandyholmes.github.io.v55.shell-extension.zip'
      - 'https://extensions.gnome.org/extension-data/mediacontrolscliffniff.github.com.v24.shell-extension.zip'
      - 'https://extensions.gnome.org/extension-data/trayIconsReloadedselfmade.pl.v27.shell-extension.zip'
    user: cg
    home_dir: /home/{{ user }}

  tasks:
    - name: Instalar jq si no está instalado
      command: sudo dnf install jq -y

    - name: Crear directorio para las extensiones de Gnome Shell
      file:
        path: '{{ home_dir }}/.local/share/gnome-shell/extensions/'
        state: directory

    - name: Loop through extension_urls and download files
      shell: |
        TARGET_DIR="{{ home_dir }}/.local/share/gnome-shell/extensions/"
        URL_OF_YOUR_ZIP_FILE="{{ item }}"
        ZIP_FILE=$(basename "$URL_OF_YOUR_ZIP_FILE")
        if [ -e "$ZIP_FILE" ]; then
            rm "$ZIP_FILE"
        fi



        # Change to the target directory
        cd "$TARGET_DIR" || { echo "Failed to change directory"; exit 1; }

        # Download the ZIP file
        curl -o "$ZIP_FILE" "$URL_OF_YOUR_ZIP_FILE"

        # Extract the UUID from metadata.json
        UUID=$(unzip -p "$ZIP_FILE" metadata.json | jq -r .uuid)

        if [ -d "$UUID" ]; then
            rm -r "$UUID"
        fi

        echo ":::::::::::::::"
        echo "URL $URL_OF_YOUR_ZIP_FILE"
        echo "ZIP $ZIP_FILE"
        echo "UUID: $UUID"
        echo "TARGET FOLDER $TARGET_DIR"
        echo ":::::::::::::::"

        if [ ! -z "$UUID" ]; then
          rm -rf "$UUID"
          pwd
          if [ -e "$ZIP_FILE" ]; then
              unzip "$ZIP_FILE" -d "$UUID"
              sudo chown "{{ user }}:{{ user }}" "$ZIP_FILE"
              gnome-extensions install "$ZIP_FILE"
              sudo chown -R "{{ user }}:{{ user }}" "$UUID"
              #gnome-extensions enable "$UUID"
              #rm "$ZIP_FILE"
          fi
          echo "ZIP FILE: $ZIP_FILE $UUID $TARGET_DIR"
          
        fi
      loop: '{{ extension_urls }}'
      register: download_result

    - name: Comprobar que las extensiones se han instalado
      become_user: "{{ user }}"
      command: ls -A1 ~/.local/share/gnome-shell/extensions/
      register: installed_extensions

    - name: Mostrar mensaje de éxito
      debug:
        msg:
          - '::::::::::::::::::::::::::'
          - 'Extensions installed and enabled'
          - ':::::::::::::::::::::::::::::::'