- name: Update system
  hosts: localhost
  become: yes
  tasks:
    - name: updating system
      become: yes
      command: sudo dnf update -y

    - name: Clone auto-cpufreq repository
      git:
        repo: https://github.com/AdnanHodzic/auto-cpufreq.git
        dest: /tmp/auto-cpufreq
        clone: yes

    - name: Install auto-cpufreq
      become: yes
      command: sudo /tmp/auto-cpufreq/auto-cpufreq-installer
