- name: Update system
  hosts: localhost
  become: yes
  tasks:
    - name: Set system time
      shell: 'sudo date -s "$(wget --method=HEAD -qSO- --max-redirect=0 google.com 2>&1 | sed -n ''s/^ *Date: *//p'')"'
      register: date_result
      debug:
        msg: 'Date set to {{ date_result.stdout }}'

    - name: add rpm fusion free
      dnf:
        name: 'https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_distribution_major_version}}.noarch.rpm'
        state: present

    - name: reimport gpg
      shell: curl https://fedoraproject.org/fedora.gpg | sudo gpg --import

    - name: clean pacakge
      shell: sudo dnf clean packages

    - name: updating system
      become: yes
      command: sudo dnf update -y

    - name: Clone auto-cpufreq repository
      git:
        repo: https://github.com/AdnanHodzic/auto-cpufreq.git
        dest: /tmp/auto-cpufreq
        clone: yes

    - name: Install auto-cpufreq
      become: yes
      shell: sudo echo "i" | /tmp/auto-cpufreq/auto-cpufreq-installer
