- name: Update system
  hosts: localhost
  become: yes
  tasks:
    - name: Set current time frm internet
      uri:
        url: https://www.google.com
        method: HEAD
        return_content: yes

    - name: Set system time
      command: sudo date -s "{{ uri_result.content | from_json | json.get('Date') }}"

    - name: add rpm fusion
      shell: /
        sudo dnf install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
        sudo dnf install https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

    - name: reimport gpg
      shell: curl https://fedoraproject.org/fedora.gpg | sudo gpg --import

    - name: clean pacakge
      shell: sudo dnf clean packages

    - name: updating system
      become: yes
      command: sudo dnf update -y

    - name: Clone auto-cpufreq repository
      git:
        repo: https://github.com/AdnanHodzic/auto-cpufreq.git
        dest: /tmp/auto-cpufreq
        clone: yes

    - name: Install auto-cpufreq
      become: yes
      shell: sudo echo "i" | /tmp/auto-cpufreq/auto-cpufreq-installer
